org: aaronbuxbaum
app: opinion-modeling-app
service: opinion-modeling

provider:
  name: aws
  region: us-east-1
  memorySize: 128
  runtime: nodejs12.x
  prefix: "opinion-modeling"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

custom:
  webpack:
    packager: yarn
    sourcemaps: false
    includeModules:
      packagePath: '../package.json'
  prune:
    automatic: true
    includeLayers: true
    number: 1

package:
  excludeDevDependencies: false

functions:
  graphql:
    handler: .nexus/build/api/app.graphql
    events:
      - http:
          path: graphql
          method: get
      - http:
          path: graphql
          method: post
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  playground:
    handler: .nexus/build/api/app.playground
    events:
      - http:
          path: playground
          method: get
